import "../globals.css";
import { ThemeProvider } from "next-themes";
import { cookies } from "next/headers";

import { Toaster } from "@/components/ui/toaster";
import ReactQueryProvider from "../providers/ReactQueryProvider";

export const metadata = {
  title: "Kasir Apps",
  description: "Generated by create next app",
};

export default function AuthAdminLayout({ children }) {
  const cookieStore = cookies();

  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <ReactQueryProvider>
            {children && (
              <div className="mx-auto container md:px-5 my-10">{children}</div>
            )}
            <Toaster />
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
