import { AppSidebar } from "@/components/AppSidebar";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeProvider } from "next-themes";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";

  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <SidebarProvider defaultOpen={defaultOpen}>
            {/* Sidebar and Trigger */}
            <AppSidebar />
            <SidebarTrigger />
            {/* Main Content */}
            {children && (
              <div className="mx-auto container md:px-5 my-10">{children}</div>
            )}
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
