import { AppSidebar } from "@/components/AppSidebar";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeProvider } from "next-themes";
import { cookies } from "next/headers";

import { Toaster } from "@/components/ui/toaster";
import ReactQueryProvider from "./providers/ReactQueryProvider";

export const metadata = {
  title: "Kasir Apps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";

  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <ReactQueryProvider>
            <SidebarProvider defaultOpen={defaultOpen}>
              {/* Sidebar and Trigger */}
              <AppSidebar />
              <SidebarTrigger />
              {/* Main Content */}
              {children && (
                <div className="mx-auto container md:px-5 my-10">
                  {children}
                </div>
              )}
              <Toaster />
            </SidebarProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
