// import "@/app/globals.css";
// import { ThemeProvider } from "next-themes";
// import { cookies } from "next/headers";

// import { Toaster } from "@/components/ui/toaster";
// import ReactQueryProvider from "../providers/ReactQueryProvider";
// import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
// import { AppSidebar } from "@/components/AppSidebar";
// import AdminNavbar from "@/components/admin-navbar/AdminNavbar";
// import { verifyJwt } from "@/lib/verifyJwt";
// import { PrismaClient } from "@prisma/client";

// export const metadata = {
//   title: "Kasir Apps",
//   description: "Generated by create next app",
// };

// const prisma = new PrismaClient();

// export default async function AdminLayout({ children }) {
//   const cookieStore = cookies();
//   const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";
//   const token = cookieStore.get("token")?.value;

//   const jwtUser = token ? await verifyJwt(token) : null;

//   let namaPegawai = null;

//   if (jwtUser?.pegawai_id) {
//     const pegawai = await prisma.pegawai.findUnique({
//       where: { id: jwtUser.pegawai_id },
//       select: { nama_pegawai: true },
//     });

//     namaPegawai = pegawai?.nama_pegawai;
//   }

//   return (
//     <html lang="en">
//       <body>
//         <ThemeProvider attribute="class" defaultTheme="dark">
//           <ReactQueryProvider>
//             <SidebarProvider defaultOpen={defaultOpen}>
//               <AppSidebar />
//               <div className="flex flex-col w-full min-h-screen">
//                 <AdminNavbar
//                   user={{
//                     nama: namaPegawai,
//                     role: jwtUser?.role,
//                   }}
//                 />

//                 <main className="flex-1 mx-auto container md:px-5 my-6">
//                   {children}
//                 </main>
//                 <SidebarTrigger />
//               </div>
//               <Toaster />
//             </SidebarProvider>
//           </ReactQueryProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

import { cookies } from "next/headers";
import { PrismaClient } from "@prisma/client";
import { verifyJwt } from "@/lib/verifyJwt";

import AdminShell from "@/components/AdminShell";
import AdminProvider from "./providers/AdminProvider";
import AdminReactQueryProvider from "./providers/AdminReactQueryProvider";

const prisma = new PrismaClient();

export default async function AdminLayout({ children }) {
  const cookieStore = cookies();
  const token = cookieStore.get("token")?.value;

  const jwtUser = token ? await verifyJwt(token) : null;

  let user = null;

  if (jwtUser?.pegawai_id) {
    const [pegawai, userRoles] = await Promise.all([
      prisma.pegawai.findUnique({
        where: { id: jwtUser.pegawai_id },
        select: { nama_pegawai: true },
      }),
      prisma.userRole.findMany({
        where: { loginpemakai_id: jwtUser.id },
        include: {
          role: {
            select: { name: true, label: true },
          },
        },
      }),
    ]);

    user = {
      nama: pegawai?.nama_pegawai,
      roles: userRoles.map((ur) => ({
        name: ur.role.name,
        label: ur.role.label,
      })),
    };
  }

  return (
    <AdminProvider>
      <AdminReactQueryProvider>
        <AdminShell user={user}>{children}</AdminShell>
      </AdminReactQueryProvider>
    </AdminProvider>
  );
}
